### ISSUE TITLE
problem with Altar doesnt work

### ISSUE THREAD

**Issue by Lascorta** [TheBusyBiscuit/Slimefun4#956]
Ancient Altar doesn't work when i put the recipe and he say this:

[Slimefun] Task #3038 for Slimefun vv4.1.15 generated an exception
--
1282 | java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/general/Particles/MC_1_8/ParticleEffect
1283 | at me.mrCookieSlime.Slimefun.AncientAltar.RitualAnimation.idle(RitualAnimation.java:64) ~[?:?]
1284 | at me.mrCookieSlime.Slimefun.AncientAltar.RitualAnimation.run(RitualAnimation.java:50) ~[?:?]
1285 | at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
1286 | at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
1287 | at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
1288 | at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
1289 | at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
1290 | at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
1291 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by WalshyDev** [comment]
Downgrade your CSCore-Lib, 1.5.16 works on 1.12
